#########################################################################
# © Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
{{ if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with $.Values.ingress.annotations }}
  annotations:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
  name: {{ print "hcf-coder-ingress-" .host  | replace "." "-" }}
spec:
  {{ if $.Values.ingress.ingressClassName }}
  ingressClassName: {{ $.Values.ingress.ingressClassName }}
  {{ end }}
  rules:
    - host: {{.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "hcf-coder.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
            path: /
            pathType: Prefix
  {{ if .tls }}
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ print "hcf-coder-cert-" .host  | replace "." "-" }}
  {{ end }}
---

{{- end }}
{{ end }}