apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcf-coder.fullname" . }}-{{ .Values.service.auxiliaryPort }}
  labels:
    {{- include "hcf-coder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.auxiliaryPort }}
      targetPort: {{ .Values.service.auxiliaryPort }}
      protocol: TCP
  selector:
    {{- include "hcf-coder.selectorLabels" . | nindent 4 }}
