apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcf-coder.fullname" . }}
  labels:
    {{- include "hcf-coder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "hcf-coder.selectorLabels" . | nindent 4 }}
