#!/bin/bash
KUBE_ONE="$HOME/.kube/kubernetesONE.config"
KUBE_TWO="$HOME/.kube/kubernetesTWO.config"
KUBECONFIG="$HOME/.kube/config"
sh -c "$GET_KUBECONFIG_ONE > \"$KUBE_ONE\""
# sh -c "$GET_KUBECONFIG_TWO > \"$KUBE_TWO\""
echo "" > $HOME/.kube/kubernetesTWO.config
echo "Merging kubeconfig files..."
KUBECONFIG=$KUBE_ONE:$KUBE_TWO kubectl config view --flatten > $KUBECONFIG